"""
FastAPI service for the customer churn prediction model.

Endpoints:
    GET  /health              -> liveness check
    GET  /model-info           -> metadata about the loaded model
    POST /predict               -> single customer churn prediction
    POST /predict/batch        -> batch prediction for multiple customers

Run locally:
    uvicorn app.main:app --reload --port 8000

Docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

from contextlib import asynccontextmanager
from pathlib import Path
from typing import List, Literal

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, ConfigDict, Field

MODEL_PATH = Path(__file__).resolve().parent.parent / "model" / "churn_model.joblib"

_artifact = None  # populated on startup via lifespan handler


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _artifact
    if not MODEL_PATH.exists():
        raise RuntimeError(
            f"Model file not found at {MODEL_PATH}. Run `python model/train.py` first."
        )
    _artifact = joblib.load(MODEL_PATH)
    yield
    _artifact = None


app = FastAPI(
    title="Customer Churn Prediction API",
    description="Predicts the probability that a telecom customer will churn, "
    "based on account and service attributes.",
    version="1.0.0",
    lifespan=lifespan,
)


class CustomerFeatures(BaseModel):
    gender: Literal["Male", "Female"]
    senior_citizen: Literal[0, 1]
    partner: Literal["Yes", "No"]
    dependents: Literal["Yes", "No"]
    tenure_months: int = Field(..., ge=0, le=100)
    phone_service: Literal["Yes", "No"]
    multiple_lines: Literal["Yes", "No", "No phone service"]
    internet_service: Literal["DSL", "Fiber optic", "No"]
    online_security: Literal["Yes", "No", "No internet service"]
    online_backup: Literal["Yes", "No", "No internet service"]
    device_protection: Literal["Yes", "No", "No internet service"]
    tech_support: Literal["Yes", "No", "No internet service"]
    streaming_tv: Literal["Yes", "No", "No internet service"]
    streaming_movies: Literal["Yes", "No", "No internet service"]
    contract: Literal["Month-to-month", "One year", "Two year"]
    paperless_billing: Literal["Yes", "No"]
    payment_method: Literal[
        "Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"
    ]
    monthly_charges: float = Field(..., ge=0)
    total_charges: float = Field(..., ge=0)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "gender": "Female",
                "senior_citizen": 0,
                "partner": "Yes",
                "dependents": "No",
                "tenure_months": 3,
                "phone_service": "Yes",
                "multiple_lines": "No",
                "internet_service": "Fiber optic",
                "online_security": "No",
                "online_backup": "No",
                "device_protection": "No",
                "tech_support": "No",
                "streaming_tv": "Yes",
                "streaming_movies": "Yes",
                "contract": "Month-to-month",
                "paperless_billing": "Yes",
                "payment_method": "Electronic check",
                "monthly_charges": 89.5,
                "total_charges": 268.5,
            }
        }
    )


class PredictionResponse(BaseModel):
    churn_probability: float
    churn_prediction: Literal["Yes", "No"]
    risk_tier: Literal["Low", "Medium", "High"]
    threshold_used: float


def _risk_tier(prob: float) -> str:
    if prob < 0.3:
        return "Low"
    if prob < 0.6:
        return "Medium"
    return "High"


def _predict_one(features: CustomerFeatures) -> PredictionResponse:
    row = pd.DataFrame([features.model_dump()])[_artifact["feature_cols"]]
    proba = float(_artifact["pipeline"].predict_proba(row)[:, 1][0])
    threshold = _artifact["threshold"]
    return PredictionResponse(
        churn_probability=round(proba, 4),
        churn_prediction="Yes" if proba >= threshold else "No",
        risk_tier=_risk_tier(proba),
        threshold_used=threshold,
    )


@app.get("/health")
def health():
    return {"status": "ok", "model_loaded": _artifact is not None}


@app.get("/model-info")
def model_info():
    if _artifact is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    return {
        "trained_at": _artifact["trained_at"],
        "threshold": _artifact["threshold"],
        "n_features": len(_artifact["feature_cols"]),
    }


@app.post("/predict", response_model=PredictionResponse)
def predict(customer: CustomerFeatures):
    if _artifact is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    return _predict_one(customer)


@app.post("/predict/batch", response_model=List[PredictionResponse])
def predict_batch(customers: List[CustomerFeatures]):
    if _artifact is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    if len(customers) > 500:
        raise HTTPException(status_code=400, detail="Batch size limited to 500 customers per request")
    return [_predict_one(c) for c in customers]
